server:
  port: 8020
  tomcat:
    max-threads: 1000
    max-connections: 20000
spring:
  application:
    name: ColorNote
  datasource:
    druid:
      url: jdbc:mysql://192.168.184.130:3306/ColorNote?characterEncoding=UTF-8&useUnicode=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 100
      max-active: 1000
      max-wait: 200
      min-idle: 20
      filter:
        commons-log:
          enabled: true
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      remove-abandoned: true
      validation-query: SELECT 1
      removeAbandonedTimeout: 180
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: validate
  redis:
    lettuce:
      pool:
        min-idle: 50
        max-idle: 500
    host: 192.168.184.130
    port: 6379
    database: 0
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.bluefatty.domain